server:
  port: 8084

aws:
  endpoint: ${AWS_ENDPOINT}
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESSKEY}
  secret-key: ${AWS_SECRETKEY}
  sqs:
    queue-url: ${AWS_SQS_QUEUE_URL}
  dynamodb:
    table-name: ${AWS_DYNAMODB_TABLE}

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics