server:
  port: 8083

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    consumer:
      group-id: delivery-grupo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics